# Generated by Django 2.1 on 2018-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hamd', '0002_artist_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
